### ISSUE TITLE
Reach a given score

### ISSUE THREAD

**Issue by SureshKamediya** [WebClub-NITK/Hacktoberfest-2k20#1]
## **BASIC** 
Dynamic programming is an idea to simply store the results of subproblems, so that we do not have to re-compute them when needed later, or you can say that it is mainly an optimization over plain recursion.

Ex-
long int fact(long int x)
{
    if(x==0)
	return 1;                       Recursion
    return x*fact(x-1);
}

long int dp[MAXN]

long int fact(long int x)
{
    if(x==0)
	return 1;                       Dynammic programming
    if(dp[x]!=-1)
	return dp[x];
    return (dp[x]=x*fact(x-1));
}

## **Description**
 	  
Given a total score n, where you can score 3,5,or 7 in one move, come up with a method to find the number of distinct combinations to reach the given score.

Note:
Suppose n=8,then {3,5} or {5,3} are equivalent. They are not to be counted separately.

## **Details**

    • Technical Specifications:Prefarabe languages are C/C++.	
    • Type of issue :Single 
    • Time Limit: 1 day. 

## **Resources**

[https://www.geeksforgeeks.org/dynamic-programming/](https://www.geeksforgeeks.org/dynamic-programming/)

## **Directory Structure**

Create a folder named 'no'("no"as in the issue number) in 'algorithms' folder. Name your program file as 'reached_score.cpp' or
'reached_score.c' accordingly. Add this program file to the folder '/algorithms/no'.

## **Note**

Please claim the issue first by commenting here before starting to work on it.

## **For co-ordinators/maintainers creating the issues**

While submitting a PR, request a review from [@SureshKamediya](https://www.geeksforgeeks.org/dynamic-programming/).Doubts and clarifications are welcome.

**Comment by Bharadwaja92** [comment]
Hi @SureshKamediya Can I work on this?

**Comment by SureshKamediya** [comment]
@Bharadwaja92 Sure! go ahead.But please stick to the time limit.
