### ISSUE TITLE
Minimum moves of a knight

### ISSUE THREAD

**Issue by Shreya301** [WebClub-NITK/Hacktoberfest-2k20#10]
### Description
Given a square chessboard of 8 x 8 size, the initial position  of a Knight and position of a target destination ((1,1) being the bottom left square and (8,8) the top right, column number is first coordinate and row number is the second), find the minimum moves the knight needs to make to reach the target position using BFS.
Example: 
Input: 1,1 
           8,8
Output: 6

### Details
- Technical Specifications: preferred languages: C/Java
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- Implement the task using BFS

### Resources
https://www.geeksforgeeks.org/possible-moves-knight/?ref=lbp
https://www.tutorialspoint.com/data_structures_algorithms/breadth_first_traversal.htm

### Directory Structure
Create a new folder called "10_knight_moves" inside algorithms folder and add the code file related to this issue in the algorithms/10_knight_moves.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @Shreya301 to request a review.

**Comment by buttercrab** [comment]
Can I do this task?

**Comment by vedanttttt** [comment]
Please assign it to me , I can do this .

**Comment by Shreya301** [comment]
@buttercrab sure go ahead!
