### ISSUE TITLE
Approximation of pi using OpenMP

### ISSUE THREAD

**Issue by SaiKrishna1207** [WebClub-NITK/Hacktoberfest-2k20#106]
### Description
The task of this program will be to arrive at an approximate value of π. The value of π is given by the following integral:

π = ∫ 4dx / (1 + x^2), with the limits of integration being 1 and 0.

This can be approximated as the sum of the areas of rectangles under the curve shown in this [figure](https://www.google.com/url?sa=i&url=https%3A%2F%2Fcis.gvsu.edu%2F~wolffe%2Fcourses%2Fcs380b%2Flabs%2Fproject_09.html&psig=AOvVaw3VxsgVk28r9dlmHPPMP-ie&ust=1602566473949000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJCh_L-nruwCFQAAAAAdAAAAABAD). 

The sample serial code is given below : 
```
static long num_steps = 100000;
double step;
void main ()
{
    int i;
    double x, pi, sum = 0.0;
    step = 1.0/(double)num_steps;
    for (i=0; i<num_steps; i++) {
        x = (i+0.5)*step;
        sum = sum + 4.0/(1.0+x*x);
    }
    pi = step * sum;
}
```
### Details
- Technical Specifications: OpenMP in C/C++.
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- (1) Make a naive implementation using the pragma parallel construct as well as atomics to prevent race conditions.
- (2) Use work-sharing and reduction to improve the speed of the code.

### Resources
- [OpenMP Reference Docs](https://www.openmp.org/wp-content/uploads/OpenMP-4.5-1115-CPP-web.pdf)
- [An Introduction to OpenMP course](https://www.youtube.com/playlist?list=PLLX-Q6B8xqZ8n8bwjGdzBJ25X2utwnoEG)

### Directory Structure
Create a new folder called "OpenMP Pi" inside Systems folder and add all the code related to this issue in Systems/106_OpenMP_Pi.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @SaiKrishna1207 to request a review.

**Comment by KangHyeoni** [comment]
Could you assign it to me?

**Comment by SaiKrishna1207** [comment]
Yeah sure go ahead.
