### ISSUE TITLE
Percolation using union-find

### ISSUE THREAD

**Issue by Shreya301** [WebClub-NITK/Hacktoberfest-2k20#11]
### Description
Consider a percolation model as a grid of NxN sites, with each site is open with the probability p. Find the probability that the system percolates. System percolates iff top and bottom are connected by open sites. When p=0, system never percolates (all sites are closed) when p=1, system always percolates (all sites are open). For large N, there will be a sharp threshold p*, after which the system almost certainly percolates. Find this threshold using the computational approach of monte carlo simulation.
Initialize N-by-N grid of sites as blocked (p=0). Randomly open sites until system percolates. Percentage of open sites gives an estimate of p*

### Details
- Technical Specifications: preferred languages: C/Java
- Type of issue: Single
- Time Limit: 1 days

### Issue requirements / progress
- [ ]  Implement this efficiently using the union-find data structure
- [ ]  Properly document the code implemented.

### Resources
https://introcs.cs.princeton.edu/java/24percolation/
https://algs4.cs.princeton.edu/15uf/
https://www2.cs.duke.edu/courses/cps100r/spring18/notes/0228/13-percolation-uf.pdf

### Directory Structure
Create a new folder called "11_percolation" inside algorithms folder and add the code file related to this issue in the algorithms/11_percolation.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @Shreya301 to request a review.

**Comment by dipanshug124** [comment]
Please assign this to me

**Comment by Shreya301** [comment]
Go ahead!

**Comment by dipanshug124** [comment]
@Shreya301 please assign it to me

**Comment by Shreya301** [comment]
As of now we are simply assigning issues by way of request, so you can go ahead with solving this @dipanshug124
