### ISSUE TITLE
Longest Increasing Subsequence

### ISSUE THREAD

**Issue by rakki-18** [WebClub-NITK/Hacktoberfest-2k20#114]
### Description
Write an efficient algorithm to find the longest increasing subsequence of a given vector

### Details
- Technical Specifications:  C/C++ preferred
- Type of issue: Multiple
- Time Limit: 3 days

### Issue requirements / progress
Follow this template 
```
vector<int> longestIncreasingSubsequence(vector<int> inputVector){
           // your code here
}
```
- [x] Write an algorithm that finds longest increasing subsequence in O(n^2) time complexity.
- [x] Write an algorithm that finds longest increasing subsequence in O(nlog(n)) time complexity.

### Resources
https://en.wikipedia.org/wiki/Longest_increasing_subsequence

### Directory Structure
Make a folder named "Longest_Increasing_Subsequence" in the "Algorithms" folder and put all your code inside the Algorithms/Longest_Increasing_Subsequence folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @rakki-18 to request a review.

**Comment by KangHyeoni** [comment]
Could you assign this to me?

**Comment by shouvikch97** [comment]
To achieve O(nlogn) time complexity, one needs a partial idea of Patience Sorting. I may be able to help. Will you please assign this to me?

**Comment by rakki-18** [comment]
@KangHyeoni Please mention which task u are going to be working on .

**Comment by rakki-18** [comment]
@shouvikch97 Sure, go ahead!

**Comment by KangHyeoni** [comment]
@rakki-18 I can do both, but I think that other person is trying to work on O(nlogn) algorithm. So I'm going to work on O(n^2) method. : ) Will you assign it to me?

**Comment by rakki-18** [comment]
@KangHyeoni Ok go ahead .
