### ISSUE TITLE
Overlapping rectangle

### ISSUE THREAD

**Issue by viveshy** [WebClub-NITK/Hacktoberfest-2k20#118]
### Description
Given two rectangles, find if the given two rectangles overlap or not.
Note that a rectangle can be represented by two coordinates, top left, and bottom right. So mainly we are given the following four coordinates.
l1: Top Left coordinate of the first rectangle.
r1: Bottom Right coordinate of the first rectangle.
l2: Top Left coordinate of the second rectangle.
r2: Bottom Right coordinate of the second rectangle.

### Details
- Technical Specifications: Any programming language
- Type of issue: Single
- Time Limit: 24 hours from the time when issue is assigned

### Issue requirements / progress
- [ ] Task 1. Input should be dynamic.
- [ ] Task 2. Add  screenshots of dynamic input, and output

### Directory Structure
Create a directory by the name "118_Overlapping_Rectangle" in the Algorithm folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @viveshCodes  to request a review.

**Comment by SPandeyCodes** [comment]
hey @viveshCodes . Can i work on this issue?

**Comment by viveshy** [comment]
@SPandeyCodes you can go ahead.
