### ISSUE TITLE
Inversions of a permutation

### ISSUE THREAD

**Issue by pranavdv** [WebClub-NITK/Hacktoberfest-2k20#12]
### Description

Given a permutation of integers from 1 to n, find the number of inversions for each integer. An inversion for an element p[i] is an index j such that, j<i and p[j]>p[i]. 

For example,
**Input:**
5
4 1 5 3 2

**Output:**
1 3 2 0 0

**Explanation:**
Consider p[i]=3. There are 2 elements to its left which are greater than it. Thus there are 2 inversions for 3.

### Details 

- Technical specifications : C/C++
- Type of issue : Single 
- Time limit : 2 days

### Issue requirements

- [ ] Write a function which runs in **O(NlogN)** time. Refer to the following template.

`vector<int> findInversions(int n,vector<int> p){ }`

### Resources 

- https://mathworld.wolfram.com/PermutationInversion.html
- http://www.cplusplus.com/reference/set/set/
- https://www.hackerearth.com/practice/data-structures/advanced-data-structures/segment-trees/tutorial/
- https://www.tutorialspoint.com/data_structures_algorithms/merge_sort_algorithm.htm

### Directory structure

Create a new folder called "12_Inversions_of_a_permutation"  inside algorithms folder and add all the code related to this issue in algorithms/12_Inversions_of_a_permutation.

**Note** 
1.Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @pranavdv to request a review.

**Comment by buttercrab** [comment]
Can I do this task?

**Comment by dipanshug124** [comment]
Please assign this to me
