### ISSUE TITLE
Implement power function

### ISSUE THREAD

**Issue by amukh18** [WebClub-NITK/Hacktoberfest-2k20#128]
### Description
Implement the `pow` function where  `pow(x,n)` = x^n. 

NOTE: Do not use the inbuilt `pow()` function anywhere in your code.

Constraints:
-   100.0 < x < 100.0
-  -2^31 <= n <= 2^31-1
-  -10^4 <= x^n <= 10^4

    
### Details
- Technical Specifications:
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Complete the given task

### Resources
N/A

### Directory Structure

In the `Algorithms` directory, create a directory named `implement_pow` and post your solution file in that directory.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @amukh18 to request a review.

**Comment by Ares358** [comment]
I would like to take this issue.

**Comment by amukh18** [comment]
Go ahead!
