### ISSUE TITLE
Matrix wipeout

### ISSUE THREAD

**Issue by amukh18** [WebClub-NITK/Hacktoberfest-2k20#129]
### Description

Suppose you are given a  matrix of dimensions `mxn`. Write a program that converts the values of all cells in the row and column of a cell to 0 if the value in that cell is 0.

- Technical Specifications:
  - Type of issue: Single
  - Time Limit: 2 days

Constraints:
  - 1 <= m, n <= 200
  - The value of any cell in the given matrix is between `-2^31` and `2^31-1` (inclusive).
### Issue requirements / progress
- [ ] Write a program for the given problem statement

### Resources
N/A

### Directory Structure
In the `Algorithms` folder, create a directory named `matrix_wipeout` and add your solution file to it.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @amukh18 to request a review.

**Comment by SPandeyCodes** [comment]
hey @amukh18 , Assign this to me.

**Comment by amukh18** [comment]
Go ahead, @SPandeyCodes !
