### ISSUE TITLE
Stack with max

### ISSUE THREAD

**Issue by srujangit123** [WebClub-NITK/Hacktoberfest-2k20#13]
### Description
Implement stack with operations push, pop, get_max where get_max function gives the maximum element in the stack.

### Details
- Technical Specifications: Preferred languages : C/C++, python, javascript
- Type of issue: Single
- Time Limit: 1 day after being assigned the issue.

### Issue requirements / progress
- Implement the task efficiently

### Resources
- https://www.geeksforgeeks.org/stack-data-structure-introduction-program/

### Directory Structure
Create a folder 13_stack_with_max under Algorithms folder and place your code file inside the 11_stack_with_max folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @srujangit123 to request a review.

**Comment by Pratap2018** [comment]
I want to work on this using python

**Comment by Rishabh186** [comment]
I want to work on this in cpp

**Comment by sathwikveeramaneni** [comment]
i want to work on this

**Comment by srujangit123** [comment]
@Pratap2018 Go ahead

**Comment by srujangit123** [comment]
@Pratap2018 Can you get the maximum in O(1). It should be O(1) after each push, pop operations

**Comment by Pratap2018** [comment]
sure i will do it

**Comment by srujangit123** [comment]
Also make sure you put your file inside 13_stack_with_max folder under Algorithms

**Comment by Pratap2018** [comment]
> Also make sure you put your file inside 13_stack_with_max folder under Algorithms
I did it and created pull request and improved Efficiency to O(1)

**Comment by krithikvaidya** [comment]
@srujangit123 closing the issue since the PR has been merged.
