### ISSUE TITLE
Disjoint set union with path compression

### ISSUE THREAD

**Issue by srujangit123** [WebClub-NITK/Hacktoberfest-2k20#14]
### Description
Implement disjoint set data structure with operations union(with path compression) and find.

### Details
- Technical Specifications: Preferred Languages: C/C++, python, javascript
- Type of issue: Single
- Time Limit: 1 day after being assigned the issue.

### Issue requirements / progress
- Write an efficient program.

### Resources
https://www.hackerearth.com/practice/data-structures/disjoint-data-strutures/basics-of-disjoint-data-structures/tutorial/

### Directory Structure
Create a folder 14_disjoint_set inside Algorithms folder and put your file inside the 14_disjoint_set folder

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @srujangit123 to request a review.

**Comment by dipanshug124** [comment]
@srujangit123 Please assign this to me

**Comment by srujangit123** [comment]
Yeah sure. Go ahead @dipanshug124

**Comment by dipanshug124** [comment]
@srujangit123 Please check if assign is done properly? I can't see my name in assignee
