### ISSUE TITLE
BFS with primes

### ISSUE THREAD

**Issue by ZerothKing** [WebClub-NITK/Hacktoberfest-2k20#18]
### Description
Given two prime numbers a and b you have to find out the number of step required to convert one prime to another.
In one step you can change a **single digit** of the number but the catch is that the resulting number should be **prime**. If you can convert the first prime(a) to the second(b) then give the number of steps required else say "IMPOSSIBLE"

For example,
**Input**:
1033 8179

**Output**:
6

**Explanation**:
1033 -> 1733 -> 3733 -> 3739 -> 3779 -> 8779 -> 8179  
        
### Details
- Technical Specifications: C/C++
- Type of issue: Single
- Time Limit: 3 days

### Issue requirements / progress
- [ ] Think of a way to generate a graph.
- [ ] Use BFS to traverse it and find the required distance.

### Resources
https://cp-algorithms.com/graph/breadth-first-search.html

### Directory Structure
Create a new folder called "18_BFS_with_primes" inside algorithms folder and add all the code related to this issue in algorithms/18_BFS_with_primes.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @ZerothKing to request a review.

**Comment by dipanshug124** [comment]
@ZerothKing Please assign this to me

**Comment by sravanireddy1102** [comment]
Hey!Can I work on this?

**Comment by shumbul** [comment]
I want to work on this. Please assign this to me.

**Comment by krithikvaidya** [comment]
@ZerothKing closing the issue since the PR is merged.
