### ISSUE TITLE
Tree Diameter

### ISSUE THREAD

**Issue by rakki-18** [WebClub-NITK/Hacktoberfest-2k20#2]
### Description
Write an efficient code to find the diameter of a tree
### Details
- Technical Specifications: C/C++
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [x] Implementing an algorithm to find the diameter of a tree

### Resources
https://www.hackerearth.com/practice/algorithms/graphs/depth-first-search/tutorial/
### Directory Structure
Create a new folder called "2_Tree_Diameter" inside algorithms folder and add all code related to this issue in the algorithms/2_Tree_Diameter folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.

Feel free to contact @rakki-18 in case of queries or for a review request

**Comment by probhav** [comment]
I'll like to claim the issue. Happy to contribute!

**Comment by shubhamptw** [comment]
I'd like to claim the issue. I'd write simple and self explanatory code for it.

**Comment by shibrahmachari** [comment]
can i claim this?

**Comment by rakki-18** [comment]
@probhav  Sure, I am assigning it you.  Please stick to the time limit

**Comment by rakki-18** [comment]
@shubhamptw I am assigning it to you

**Comment by krithikvaidya** [comment]
@rakki-18 I'll close the issue since the PR has been merged.
