### ISSUE TITLE
COVID-19  Data Visualization

### ISSUE THREAD

**Issue by muditsinghal** [WebClub-NITK/Hacktoberfest-2k20#21]
### Description
Create an IPython Notebook to visualize COVID-19 Data using pandas and matplotlib. 
### Details
- Technical Specifications: Python, Jupyter Notebook
- Type of issue: Single 
- Time Limit: 48 Hours

### Issue requirements / progress
- [ ] Task 1. Extract the CSV file using the link given below.
- [ ] Task 2. Prepare the Dataframes for Data Visualization using pandas.
- [ ] Task 3. Create Visualizations using matplotlib.
### Resources
List of resources that might be required / helpful.
[Raw Data]( https://raw.githubusercontent.com/datasets/covid-19/master/data/countries-aggregated.csv)
[Jupyter Notebook Tutorial](https://www.dataquest.io/blog/jupyter-notebook-tutorial/)
[Pandas Tutorial](https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python)
[Matplotlib Tutorial](https://www.datacamp.com/community/tutorials/matplotlib-tutorial-python)

### Directory Structure
Within this repository's 'machine learning' folder, create a folder called 'Covid-19 Data Visualization' (if it doesn't exist yet). Within this folder, place the file/folder in which you have written the program for the task, named appropriately.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @muditsinghal to request a review.

**Comment by blackfly19** [comment]
Can you please assign me this issue.

**Comment by pradumio** [comment]
I can work on this. Can you assign me?

**Comment by muditsinghal** [comment]
@blackfly19 go ahead with the issue.

**Comment by krithikvaidya** [comment]
@pradumio you can go ahead with this if you wish
