### ISSUE TITLE
Self Balancing Tree

### ISSUE THREAD

**Issue by SidharthLanka** [WebClub-NITK/Hacktoberfest-2k20#22]
### Description
An AVL tree is a self-balancing binary search tree. In an AVL tree, the heights of the two child subtrees of any node differ by at most one; if at any time they differ by more than one, rebalancing is done to restore this property.
You are given a pointer to the root of an AVL tree. Insert a value into this tree and perform the necessary rotations to ensure that it remains balanced.

### Label
Data Structures, Intermediate, Hacktoberfest

### Details
- Technical Specifications: 
- Type of issue: Single
- Time Limit: 12 hours after claiming the issue
### Issue requirements / progress
- Implement the given task.

### Resources
https://www.cs.auckland.ac.nz/software/AlgAnim/AVL.html
https://en.wikipedia.org/wiki/AVL_tree

### Directory Structure
Create a new folder "Self_Balacing_Tree" inside the "Data Structures" folder and add all the necessary files and code in "Data Structures/Self_Balancing_Tree"

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @ to request a review.

**Comment by limebell** [comment]
I'd like to work on this issue :)

**Comment by limebell** [comment]
It seems like *Directory Structure* section is missing :(

**Comment by SidharthLanka** [comment]
> I'd like to work on this issue :)

Sure, please go ahead. I didn't see this. I fixed Directory Structure part.

**Comment by krithikvaidya** [comment]
@SidharthLanka I'll close the issue since the PR has been merged.
