### ISSUE TITLE
Morse Code

### ISSUE THREAD

**Issue by Janmansh** [WebClub-NITK/Hacktoberfest-2k20#23]
### Description
Write a program which takes a string "S" as input and add a function which takes string "S" as its argument and returns the string containing morse code of "S". <br>
Also add a function which accepts morse code and returns the original text for it.

### Details
- Technical Specifications - Morse code should be stored as string.
- Type of issue: Single
- Time Limit: 2 days (This time limit will be enforced once someone has claimed the issue. If that person hasn't submitted a PR within this limit, the issue will be assigned to the person who applied next.)

### Issue requirements
- [ ] Task 1. Add a function which returns morse code of a string.
- [ ] Task 2. Add a function which decodes a morse code to  a string.

### Resources
https://www.geeksforgeeks.org/morse-code-implementation/

https://en.wikipedia.org/wiki/Morse_code

### Directory Structure
Create a new folder called "23_Morse_code" inside systems folder and add all code related to this issue in the Systems/23_Morse_code

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Feel free to contact @Janmansh for any queries or to review the request.

**Comment by raypretam** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by Janmansh** [comment]
Okay go ahead @raypretam

**Comment by RohanSahana** [comment]
Can I work on this issue?

**Comment by Janmansh** [comment]
@RohanSahana Go Ahead

**Comment by Janmansh** [comment]
@krithikvaidya I have reviewed @raypretam 's  PR. Please merge it.

**Comment by Janmansh** [comment]
@krithikvaidya  I have reviewed @RohanSahana 's PR. Please merge it.
