### ISSUE TITLE
Prefix Word Count

### ISSUE THREAD

**Issue by spectre900** [WebClub-NITK/Hacktoberfest-2k20#24]
### Description
You are given a list of valid words and for each query you will be given a prefix . Write an efficient function/algorithm that will return the number of valid words having the given word as its prefix.

### Details
- Technical Specifications: Implementation in C/C++ is preferred and for each query the runtime should be O(L) where L is the length of the given Prefix.
- Type of issue: Single
- Time Limit: One day

### Issue requirements / progress
- [ ] Implement an efficient function to count the number of words with the given prefix.

### Resources
https://www.geeksforgeeks.org/trie-insert-and-search/

### Directory Structure
Create a new folder called "24_Prefix_Word_Count" inside algorithms folder and add all the code related to this issue in algorithms/24_Prefix_Word_Count.

#### Note
 Please claim the issue first by commenting here before starting to work on it.
 Once you are done with the task and have created a Pull Request, please tag @spectre900 to request a review.

**Comment by SuyashGupte** [comment]
I want to work on this

**Comment by SuyashGupte** [comment]
can I write program for this in python?

**Comment by ankur-kayal** [comment]
I can work on this issue. I can implement this in c++. @spectre900 . Please assign me 👍

**Comment by spectre900** [comment]
@SuyashGupte
 ya sure ....go ahead
