### ISSUE TITLE
Implement fibonacci search in C++

### ISSUE THREAD

**Issue by suhasks123** [WebClub-NITK/Hacktoberfest-2k20#25]
### Description
Fibonacci search is an algorithm for searching an element in an array. It is a comparison-based technique that uses Fibonacci numbers to search an element in a sorted array. It uses a divide and conquer strategy similar to binary search.

### Details
- Technical Specifications: 
- Type of issue: Single
- Time Limit: 24 hours

### Issue requirements / progress
Implement a function to search an element in an array using Fibonacci search. The function should be of the form:
```C++
int FibonacciSearch(int arr[], int target) {

}
```
The function returns the index of the element in the array if found and -1 if not found. Write an appropriate driver `main()` function for taking proper input from `stdin`, calling the search function and printing proper output to `stdout`.

Implementation can be done in C/C++. The time complexity of the implementation should be O(log n).

### Directory Structure
Inside the 'Algorithms' folder in this repository, create a folder called '25_Fibonacci_Search' (if it doesn't exist yet). Place the file containing your implementation inside this folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @suhasks123 to request a review.

**Comment by ankur-kayal** [comment]
Can i work on this issue?
Questions: 
1. Can i use vectors instead of arrays?
2. Do i have to take input from user and write output to the console?
@suhasks123

**Comment by Harjot9812** [comment]
i am working

**Comment by ankur-kayal** [comment]
@Harjot9812 how can you work? You havent claimed the issue yet

**Comment by suhasks123** [comment]
@ankur-kayal You can start working on the issue

To answer your queries,
1. Yes, you can use vectors
2. Yes, take input from the user and write appropriate output to the console

**Comment by suhasks123** [comment]
@Harjot9812 Please claim the issue before working on it

**Comment by Harjot9812** [comment]
I forget sorry. Can you plz not dismiss my pull request. ankur can add on my file  
@suhasks123

**Comment by ankur-kayal** [comment]
@suhasks123 thank you for assigning this and clarifying my doubts 👍

**Comment by suhasks123** [comment]
@Harjot9812 Sorry, the issue has to be assigned to you for your PR to be considered

**Comment by ankur-kayal** [comment]
@suhasks123 Pull request created.
