### ISSUE TITLE
Hash Table implementation

### ISSUE THREAD

**Issue by SaiKrishna1207** [WebClub-NITK/Hacktoberfest-2k20#29]
### Description
Create a simple implementation of a hash table in C/C++/Java using any data structure required. A simple hash function can be used and progressively improved with time. The hash table should have the following 3 functions - Insert, Delete and Retrieve. These functions should be implemented independent of each other. Any data structure can be used. There is no restriction on the hash function or the method to address the conflict. Each key has multiple data items associated with it.

### Details
- Technical Specifications: Knowledge of C/C++/Java data structures
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- Create a simple hash table with the 3 functions - void Delete(key), void Insert(key), <return_type> Retrieve(key)., where <return_type> is the type of data associated with it. The return type can be made void and the data to be retrieved can be simply be displayed/printed in the Retrieve() function. 
- Additional functions like Update() and helper functions like DisplayTable() can be created once the basic functionality sets in.

### Resources
- https://www.tutorialspoint.com/data_structures_algorithms/hash_table_program_in_c.htm
- https://www.youtube.com/watch?v=m6n_rozU8dA

### Directory Structure
Inside the 'Algorithms' folder in this repository, create a folder called '29_Hash_Table_Implementation' (if it doesn't exist yet). Place the file containing your implementation inside this folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @SaiKrishna1207 to request a review.

**Comment by praj1wal** [comment]
I want to work on this.

**Comment by SaiKrishna1207** [comment]
Sure, go ahead. Please follow the aforementioned steps described above.

**Comment by krithikvaidya** [comment]
@SaiKrishna1207 I'll close the issue since the PR has been merged.
