### ISSUE TITLE
Exploring REST API

### ISSUE THREAD

**Issue by viveshy** [WebClub-NITK/Hacktoberfest-2k20#35]
### Description
Create a REST API in your favorite programming language which should include at least four HTTP methods ( GET, POST, PUT, DELETE, etc).

### Details
- Technical Specifications: Any programming language
- Time Limit: 48 hours from the time of assignment

### Issue requirements / progress
- [x] REST API with any four HTTP methods.

### Resources
You can refer to some of the following resources:
- [Understanding REST API](https://www.smashingmagazine.com/2018/01/understanding-using-rest-api/)
- [Sending HTTP request](https://learning.postman.com/docs/getting-started/sending-the-first-request/)

### Directory Structure
Create a folder with the name **35_REST_API** inside the **Development** folder and put all the relevant files in it.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @viveshCodes  to request a review.

**Comment by KushGrandhi** [comment]
@viveshCodes  please assign this to me

**Comment by viveshy** [comment]
@KushGrandhi You can go ahead. Happy coding!

**Comment by mohitshende** [comment]
@viveshCodes  I would like to do this.

**Comment by viveshy** [comment]
@mohitshende It has already been assigned to @KushGrandhi . Please explore other issues on the repo.

**Comment by viveshy** [comment]
> @viveshCodes please assign this to me

Any updates on this? Since your time limit is over, we'll assign this to other.

**Comment by viveshy** [comment]
> @viveshCodes I would like to do this.

@mohitshende You can take up this issue if you like to work on it. It'll be assigned to you if you claim it before any other contributor does.

**Comment by mohitshende** [comment]
Ok I will work on this. But you seemed to have removed the hactoberfest label from the issue.

**Comment by mohitshende** [comment]
Please assign this to me.

**Comment by viveshy** [comment]
> Please assign this to me.

@mohitshende You can go ahead.

**Comment by mohitshende** [comment]
@viveshCodes I have submitted the pull request #80  ,please check.

**Comment by krithikvaidya** [comment]
@viveshCodes I'll close the issue since the PR has been merged.
