### ISSUE TITLE
Check if a binary tree is a BST

### ISSUE THREAD

**Issue by Aryaman2912** [WebClub-NITK/Hacktoberfest-2k20#37]
### Description
Write code for an efficient algorithm to check if a binary tree is a binary search tree.

### Details
- Technical Specifications: Design an algorithm that is most efficient both in terms of time and space.
- Type of issue: Single
- Time Limit: 2 Days
### Issue requirements / progress
- [ ] Implement an algorithm to check if a binary tree is a BST

### Resources
https://www.geeksforgeeks.org/a-program-to-check-if-a-binary-tree-is-bst-or-not/

### Directory Structure
Create a new folder "37_Is_Binary_Tree_BST" inside the "Algorithms" folder and add all the necessary files and code in Algorithms/37_Is_Binary_Tree_BST

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Feel free to contact @Aryaman2912 for any clarifications or for a review

**Comment by raypretam** [comment]
I want to work on this. Please assign it to me.

**Comment by Aryaman2912** [comment]
@raypretam Sure, go ahead.

**Comment by AbhiswasPatil** [comment]
Can I work on this ??

**Comment by Aryaman2912** [comment]
@AbhiswasPatil Okay, go ahead. Please stick to the time limit.

**Comment by bhawesh96** [comment]
@Aryaman2912 , looks like this is stale. Can I pick this up?

**Comment by Aryaman2912** [comment]
@bhawesh96 Go ahead.

**Comment by Aryaman2912** [comment]
Hey @bhawesh96 could you recheck your code? It doesn't seem to work for all cases.

**Comment by bhawesh96** [comment]
@Aryaman2912 , could you please assign this issue to someone else? I'm unable to figure out the problem in my script. Maybe I'll read more about BSTs.

**Comment by Dheeraj-kumar626** [comment]
@Aryaman2912 Can I work on this ??
