### ISSUE TITLE
Bash Shell Script For encryption and decrytion of PDF File

### ISSUE THREAD

**Issue by dharmicksai** [WebClub-NITK/Hacktoberfest-2k20#38]
### Description
Make two shell scripts ,one for encryption of a PDF file and other for decryption of an encrypted PDF file. The name of PDF file that is to be encrypted/decrypted and the password must be given as arguments to the script . The script should create new encrypted/decrypted PDF file . 

### Details
- Technical Specifications: Compatible with bash shell. use qpdf package to encrypt and decrypt PDF .
- Type of issue: Single
- Time Limit: 2 days after issue is claimed.

### Issue requirements / progress
- [ ] Task 1: Make script for encryption of PDF
- [ ] Task 2: Make script for decryption of encrypted PDF .

### Resources
List of resources that might be required / helpful.
https://www.tutorialspoint.com/unix/shell_scripting.htm
https://askubuntu.com/questions/805342/qpdf-encryption-of-a-pdf-file

### Directory Structure
Inside the 'Systems' folder in this repository, create a folder called '38_PDF_encryption_and_decrption' (if it doesn't exist yet). Place both script files  for encryption and  for decryption containing your implementation inside this folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @dharmicksai to request a review.

**Comment by tiagoods** [comment]
Can you assign this issue to me?

**Comment by bhawesh96** [comment]
@dharmicksai , could you please assign this to me?

Also, I'm assuming that _qpdf_ shall be already installed in the system and environment variables set accordingly.

**Comment by dharmicksai** [comment]
@bhawesh96  , u can go ahead .
yes qpdf is already installed

**Comment by dharmicksai** [comment]
@krithikvaidya please merge thi
