### ISSUE TITLE
Affine Cipher Decryption

### ISSUE THREAD

**Issue by niranjansy** [WebClub-NITK/Hacktoberfest-2k20#39]
### Description
The Affine cipher is a type of monoalphabetic substitution cipher, which encodes each alphabet according to a mathematical function as follows : 
```
E(x) = (a*x + b) % m 
x = numerical equivalent of the letter
m = size of the alphabet
a, b = keys of the cipher
a and m must be coprime
```
Example: 
Original Text : AFFINECIPHER
Keys : a = 5, b = 8
Cipher Text : IHHWVCSWFRCP 

Write an efficient code that performs decryption of the Affine cipher, that is, given a cipher text and values of the keys, the program should return the original text. 

### Details
- Technical Specifications: Language preferences - C, C++, Python
- Type of issue: Single
- Time Limit: 2 days (This time limit will be enforced once someone has claimed the issue. If that person hasn't submitted a PR within this limit, the issue will be assigned to the person who applied next)

### Issue requirements / progress
- [ ] Write an efficient program to decrypt the Affine cipher
- [ ] Ensure that the program compiles and runs correctly on the example given above

### Resources
* [Affine Cipher Wikipedia](https://en.wikipedia.org/wiki/Affine_cipher#:~:text=The%20affine%20cipher%20is%20a,converted%20back%20to%20a%20letter.)

### Directory Structure
Create a new folder called "39_Affine_Decrypt" inside the 'Systems' folder and add the required code file in the Systems/39_Affine_Decrypt folder. 

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, tag @niranjansy to request a review.

**Comment by ritikgarg655** [comment]
Hello,
I am interested to implement function in c++ language. This can be implemented in O(n) time complexity where N is size of string. I am having question that input is STL string or array of character?

**Comment by tiagoods** [comment]
Can you assign this issue to me?

**Comment by niranjansy** [comment]
@ritikgarg655 You can go ahead and work on this. 
Since you are working in C++, you can take the input to be an STL string.

**Comment by ritikgarg655** [comment]
ok I will make it.

**Comment by Mahendra7985** [comment]
hello , i m also interested to implement this program in python .

**Comment by Aravindha1234u** [comment]
Is this issue not a part of Hacktoberfest?

**Comment by niranjansy** [comment]
@Mahendra7985 and @Aravindha1234u This issue was already assigned, since @ritikgarg655 had claimed it before you. 
It shall be assigned to one of you if @ritikgarg655 fails to complete it within the given time limit. Until then please explore other issues on the repo.

**Comment by Aravindha1234u** [comment]
But still now this not assigned to anybody that's why I created a pull request. Can you make sure whether did you assign this to him.

**Comment by niranjansy** [comment]
Yes, the issue is considered as assigned to the one who claims it first by commenting.

**Comment by Aravindha1234u** [comment]
Gotcha. Thanks for that.
