### ISSUE TITLE
Student Course Schedule

### ISSUE THREAD

**Issue by AnirudhAchal** [WebClub-NITK/Hacktoberfest-2k20#4]
### Description
You are given a list of courses that a student must complete in order to graduate from a college along with prerequisites for each of them respectively. In order to take a course, a student must first complete all of it's prerequisites. Write an efficient algorithm / function that returns any suitable order that a student can take in order to complete all the courses.

### Details
- Technical Specifications: Implement in C++, Time complexity of algorithm should be O(n + m), where n is the number of courses and m is the sum of number of the prerequistes for each course respectively.
- Type of issue: Single
- Time Limit: One day

### Issue requirements
- Write a Function that computes is an efficient way the returns a suitable order in which the student can take the courses. Follow the same template for your function as given below.

```
vector<string> get_student_course_schedule(vector<string> courses, vector<vector<string>> prerequisites) 
 {
    // Your code goes here
}
```
Note : The courses and their respective prerequisites will be given in the same order i.e the prerequisites of the ith course in 'courses' will be the ith element in 'prerequisites'

### Resources
- https://www.geeksforgeeks.org/the-c-standard-template-library-stl/
- https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/

### Directory Structure
Create a new folder called "4_Student_course_schedule" inside algorithms folder and add all code related to this issue in the algorithms/4_Student_course_scheduler. Your code must be submitted in a .cpp file.

#### Note
Please claim the issue first by commenting here before starting to work on it.

Contact us : 
@geekswaroop
@AnirudhAchal

**Comment by dipanshug124** [comment]
Please assign this to me

**Comment by AnirudhAchal** [comment]
@dipanshug124 Sure! go ahead

**Comment by viveshy** [comment]
This issue is opened again. Anyone can claim and work on it.
