### ISSUE TITLE
Modified Run-length encoding

### ISSUE THREAD

**Issue by Shree987** [WebClub-NITK/Hacktoberfest-2k20#45]
### Description
Given a string s and an integer k. You need to delete at most k characters from s such that the run-length encoded version of s has minimum length. Also note that in this case, we are not adding '1' after single characters.

Find the minimum length of the run-length encoded version of s after deleting at most k characters.

### Details
- Technical Specifications: Preferred Languages: C, C++, Python
- Type of issue: Single
- Time Limit: 2 Days

### Issue requirements / progress
- [ ] Implement an efficient algorithm to calculate the minimum length

### Resources
[Run length Encoding](https://en.wikipedia.org/wiki/Run-length_encoding)

### Directory Structure
Create a new folder "45_Modified_Run_length_Encoding" inside the "Algorithms" folder and add all the necessary files and code in "Algorithms/45_Modified_Run_length_Encoding"

#### Note
1. Please claim the issue first by commenting here before starting to work on it. Also specify the language in which you want to implement.
2. Once you are done with the task and have created a Pull Request, please tag @Shree987 to request a review.

**Comment by praj1wal** [comment]
I want to work on this. Assign this to me.

**Comment by Shree987** [comment]
Okay, go ahead @praj1wal

**Comment by Shree987** [comment]
Since, the time-limit for submission is reached and no PR is submitted, this issue is currently not assigned to anyone and is open for submissions. Kindly claim this issue before starting with PR and finish the PR submission before time-limit once you are assigned.
