### ISSUE TITLE
Breast cancer condition prediction

### ISSUE THREAD

**Issue by amukh18** [WebClub-NITK/Hacktoberfest-2k20#46]
### Description
Given the characteristics of the cell nuclei present in the image of a fine needle aspirate (FNA) of a breast mass, predict if the breast cancer tumour is malignant or benign.

The dataset contains  one id column, 30 real valued feature columns, and one string column.
Ten real-valued features are computed for each cell nucleus:

a) radius (mean of distances from center to points on the perimeter)
b) texture (standard deviation of gray-scale values)
c) perimeter
d) area
e) smoothness (local variation in radius lengths)
f) compactness (perimeter^2 / area - 1.0)
g) concavity (severity of concave portions of the contour)
h) concave points (number of concave portions of the contour)
i) symmetry
j) fractal dimension ("coastline approximation" - 1)

The mean, standard error and "worst" or largest (mean of the three
largest values) of these features were computed for each image,
resulting in 30 features. For instance, field 3 is Mean Radius, field
13 is Radius SE, field 23 is Worst Radius.

You may import the dataset using the following code:
```f
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()
```

You may also obtain the dataset from the following link:
[UCI Machine Learning repository](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29)

Output: 'M' for malignant, 'B' for benign.
### Details
- Technical Specifications: scikit-learn, jupyter notebook
- Type of issue: Multiple
- Time Limit: 2(Two) days

### Issue requirements / progress
- Use a logistic regression model on this dataset
- Use a random forest classifier model on this dataset
- Use a support vector machine model on this dataset.

### Resources
[scikit-learn logistic regression documentation: ](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
)
[scikit-learn random forest classifier documentation:](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)
[scikit-learn support vector machine documentation:
](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html)

### Directory Structure
Create a directory named `breast_cancer_prediction`.
 Inside it, create the following directories:
`logreg` for the logistic regression model
`random_forest` for the random forest model
`svm` for the support vector machine model
Put your file for each model in the respective directory.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @amukh18 to request a review.

**Comment by RohanSahana** [comment]
@amukh18 Can I work on this issue? But I have already have put a pull request for #28 issue

**Comment by amukh18** [comment]
@RohanSahana you may work on this issue. This issue and issue #28 are different issues. This is a classification problem.

**Comment by RohanSahana** [comment]
@amukh18  Ok

**Comment by RohanSahana** [comment]
As per note, I  request @amukh18 to review my pull request. The code has been modified as per your request (https://github.com/WebClub-NITK/Hacktoberfest-2k20/pull/57#issuecomment-706130303) and (https://github.com/WebClub-NITK/Hacktoberfest-2k20/pull/57#issuecomment-705471159).

**Comment by amukh18** [comment]
@RohanSahana  I have reviewed your PR. The changes are correct. Good job on your PR!
