### ISSUE TITLE
Valid Decimal Number

### ISSUE THREAD

**Issue by sravanireddy1102** [WebClub-NITK/Hacktoberfest-2k20#49]
### Description
Given a string ,you need to output true if that can be interpreted as a decimal number and false otherwise.

Following are some examples:
1. "0" => true                             
2.  "2e10" => true
3.  " 0.1 " => true                         
4. "95a54e53" => false
5.  "abc" => false                         
6.  "1 a" => false            
7.  " -90e3   " => true                    
8.  " 1e " => false                     
9.  "e3" => false                           
10.  " 6e-1" => true"           
11.  " 99e2.5 " => false                  
12.   "53.5e93" => true
13.   " --6 " => false           

Here is a list of characters that can be in a valid decimal number:
- Numbers 0-9
- Exponent - "e"
- Positive/negative sign - "+"/"-"
- Decimal point - "."

### Details
- Technical Specifications: Preferred languages Python , C++ and C
- Type of issue: Single 
- Time Limit: 4 days

### Issue requirements / progress
- [ ] Write an efficient code and check the program inputting proper test cases
- [ ] Clean code for beginners to understand

### Directory Structure
Create a folder "Valid_decimal_number" inside the "Algorithms" folder and add all the necessary code to the folder "Algorithms/Valid_decimal_number"
#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Feel free to contact @sravanireddy1102 for any clarifications

**Comment by keerti2001** [comment]
Hey!  Can you assign me this

**Comment by sravanireddy1102** [comment]
yeah!! Go ahead
assigned to @keerti2001

**Comment by keerti2001** [comment]
Hey I have made a pull request

**Comment by sravanireddy1102** [comment]
Oh great!!I will look into that
