### ISSUE TITLE
Rock Paper Scissors 

### ISSUE THREAD

**Issue by DeltaCube23** [WebClub-NITK/Hacktoberfest-2k20#5]
### Description
2 players A and B play the game of rock, paper, scissors for **n** rounds. Let [a1,a2,a3] & [b1,b2,b3] represent the number of times A and B show rock(1), scissor(2) and paper(3) respectively. It is guaranteed that a1+a2+a3 = b1+b2+b3 = n. 
1. Find the maximum number of rounds Alice can win.
2. Find the minimum number of rounds  Alice can win.
(NOTE : The sequence in which they show things is random so try finding the best case and worst case for Alice. Also if they show the same things it is a draw) 

### Details
- Technical Specifications: C/C++/Python/Java
- Type of issue: Single
- Time Limit: 24 hours

### Issue requirements / progress
1. Find the maximum number of rounds A can win.
2. Find the minimum number of rounds  A can win.
(You need to find both the answers)

### Resources
**Here are few sample cases of input and output expected from the program:**

Example 1:  n = 319; (a1, a2, a3) = (10, 53, 256); (b1, b2, b3) = (182, 103, 34)
Answer 1: Maximum Rounds A can win = 226; Minimum Rounds A can win = 119

Example 2: n = 12; (a1, a2, a3) = (3, 3, 3); (b1, b2, b3) = (3, 3, 3)
Answer 2: Maximum Rounds A can win = 9; Minimum Rounds A can win = 0

### Directory Structure
Create a new folder called "5_rock_paper_scissors" inside algorithms folder and add all code related to this issue in the algorithms/5_rock_paper_scissors.

#### Note
Please claim the issue first by commenting here before starting to work on it.
Feel free to contact @DeltaCube23 for any queries or to review the request.

**Comment by buttercrab** [comment]
Can I do this task?

**Comment by DeltaCube23** [comment]
@buttercrab sure, do go ahead.

**Comment by DineshBS44** [comment]
Can I also do this task?

**Comment by DeltaCube23** [comment]
@krithikvaidya please merge it

**Comment by DeltaCube23** [comment]
@adharshkamath please merge this
