### ISSUE TITLE
Applying Sunglasses filter on webcam feed

### ISSUE THREAD

**Issue by nishant-nayak** [WebClub-NITK/Hacktoberfest-2k20#51]
### Description
Apply a sunglasses filter on a face in the webcam feed. The sunglasses should be present in the appropriate position on the face, and should move along with the face. The image of sunglasses and the shape predictor .dat file for finding the 68 facial landmarks are provided in the resources below (first link). Make use of the `dlib` Python library in order to use the shape predictor. 

### Details
- Technical Specifications: Preferred Language is Python, some useful libraries are NumPy, OpenCV and dlib
- Type of issue: Single
- Time Limit: 2 days after assignment of the issue

### Issue requirements / progress
- [ ] Using the webcam feed and dlib's face detector, find the 68 facial landmarks.
- [ ] Find the correct angle of inclination of the eyes and the appropriate size of the sunglasses.
- [ ] Blend the rotated glasses onto the webcam feed

### Resources
- [Resources for the issue](https://drive.google.com/drive/folders/1LCnTLoEymxR9HOfXgqkJr1hAl95pzHEE?usp=sharing)
- [Finding facial landmarks](https://www.pyimagesearch.com/2017/04/03/facial-landmarks-dlib-opencv-python/)
- [NumPy Documentation](https://numpy.org/doc/stable/)
- [SciPy Multidimensional Image Processing (for rotating images)](https://docs.scipy.org/doc/scipy/reference/ndimage.html)

### Directory Structure
Create a folder named `51_sunglasses_filter` in the "Others" directory (if it doesn't already exist) and place **only the code file** in the folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @nishant-nayak to request a review.

**Comment by Bharadwaja92** [comment]
Hi @nishant-nayak , I would like to work on this issue.

**Comment by nishant-nayak** [comment]
@Bharadwaja92 sure! go ahead, feel free to ask if you have any queries/issues

**Comment by nishant-nayak** [comment]
@Bharadwaja92 I've reviewed the code and I have requested a correction in your code, please look into it at the earliest. The deadline for submission will be extended till 11:59 PM, 3rd October. Thanks!
