### ISSUE TITLE
LZW Encoding 

### ISSUE THREAD

**Issue by ph09** [WebClub-NITK/Hacktoberfest-2k20#6]
### Description
A text file has been provided in the folder. Write a program to implement LZW encoding on the input from the text file and output the final encoding and the encoding for each substring.

### Details
- Technical Specifications: Any language can be used for implementation. Python/C++ is preferred.
- Type of issue: Single.
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Implement the LZW encoding algorithm efficiently.

### Resources
- http://www.cs.columbia.edu/~allen/S14/NOTES/lzw.pdf

### Directory Structure
Create a folder named LZW in the 'algorithms' folder. 
Name your program file 'lzw.py' (depending on your language of implementation). Add this program file to the folder '/algorithms/LZW'.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
While submitting a PR, request a review from @ph09

**Comment by manakpandey** [comment]
I want to work on it.

**Comment by raypretam** [comment]
I want to work on it. Please assign it to me.
