### ISSUE TITLE
Schools During Covid-19

### ISSUE THREAD

**Issue by varun-raghavendra** [WebClub-NITK/Hacktoberfest-2k20#64]
### Description
There are **n** students in a class, and **m** friendships between them. Because of Covid19 now the students will be divided into 2 groups which will have classes on alternate days. To ensure that students don't get in contact with each other during classes, the school wants to make the groups in such a way that no two students in a group are friends. 

Your task is to find if this can be done or not.

**Input:**
The first input line has two integers **n** and **m**: the number of students and friendships. The students are numbered from 1 to n.
Then, there are **m** lines describing the friendships. Each line has two integers **a** and **b**: students a and b are friends.
Every friendship is between two different students. Note that there is at most one friendship between any two students.

**Output:**
Print how to make the groups. For each student, print **1** or **2** depending on his/her group. You can print any valid solution.
If there are no solutions, print **-1**.

### Details
- Technical Specifications: Preferred Languages: C, C++, python
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [x] Implement an efficient algorithm to perform the above task

### Resources
None

### Directory Structure
Create a new folder "64_Schools_Covid_19" inside the "Algorithms" folder and add all the necessary files and code in "Algorithms/64_Schools_Covid_19"

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @varun-raghavendra to request a review.

**Comment by ghost** [comment]
Hi, can I work on this? Can you also clarify if the two groups need to contain the same number of students?

**Comment by varun-raghavendra** [comment]
Yeah you can work on it. Also there is no such necessity that the two groups should contain the same number of students

**Comment by krithikvaidya** [comment]
@varun-raghavendra I'll close the issue since the PR has been merged.
