### ISSUE TITLE
Number of distinct substrings of a string

### ISSUE THREAD

**Issue by rak108** [WebClub-NITK/Hacktoberfest-2k20#7]
### Description
Take a string of lowercase alphabets only as input from user, and then count the number of distinct substrings of the string by using a trie.

### Details
- Technical Specifications: Prefered languages are C/C++
- Type of issue: Single 
- Time Limit: 1 day after being assigned the issue

### Issue requirements / progress
- [ ] Implement the given task efficiently.

### Resources
- https://en.wikipedia.org/wiki/Trie
- https://medium.com/basecs/trying-to-understand-tries-3ec6bede0014

### Directory Structure
Create a folder "7_Distinct-Substrings" under the "Algorithm" directory and within it add your file with the same name.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
While submitting a PR, please request a review from @rak108

**Comment by dipanshug124** [comment]
Please assign this to me

**Comment by rak108** [comment]
@dipanshug124 Sure, you can start working on this.

**Comment by krithikvaidya** [comment]
Since @dipanshug124 hasn't created a PR yet, the issue is still open to be claimed.
