### ISSUE TITLE
String Transformation

### ISSUE THREAD

**Issue by varun-raghavendra** [WebClub-NITK/Hacktoberfest-2k20#70]
### Description
Find the least number of operations required to transform a given string into another given string.
The allowed operations are:
- Add one character to the string.
- Remove one character from the string.
- Replace one character in the string.

For example, the minimum number of operations required for the strings "FALL" and "TALL" is 1, because you can replace F with T. 

Calculate the least number of operations required for two given strings.

Input:
The first input line has a string of length **n** that contains characters between A–Z.
The second input line has a string of length **m** that contains characters between A–Z.

Output:
Print the minimum number of required operations.

Constraints: 1 ≤ n, m ≤5000

### Details
- Technical Specifications: Preferred Programming Languages: C, C++, Python
- Type of issue: Single
- Time Limit: 2.5 days (This time limit will be enforced once someone has claimed the issue. If that person hasn't submitted a PR within this limit, the issue will be assigned to the person who applied next).

### Issue requirements / progress
- [ ] Implement the above task

### Resources
None

### Directory Structure
Create a new folder "70_String_Transformation" inside the "Algorithms" folder and add all the necessary files and code in "Algorithms/70_String_Transformation"

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @varun-raghavendra to request a review.

**Comment by SPandeyCodes** [comment]
Hi @varun-raghavendra . I would like to work on this issue. Assign this to me.

**Comment by AbhiswasPatil** [comment]
Can I work on this ??

**Comment by varun-raghavendra** [comment]
I'm assigning this to @SPandeyCodes

**Comment by varun-raghavendra** [comment]
This issue is open for anyone to claim again
