### ISSUE TITLE
BMI calculator with a GUI

### ISSUE THREAD

**Issue by krithikvaidya** [WebClub-NITK/Hacktoberfest-2k20#8]
### Description
Create a BMI (Body Mass Index) calculator. It should take the height (in meters) and weight (in kg) as inputs. As the output, it should show the BMI value and the category under which that height + weight combination comes under (underweight, normal healthy weight, etc.). The application should have a simple Graphical User Interface.

### Details
- Technical Specifications:
- Type of issue: Multiple
- Time Limit: 24 hours

### Issue subtasks (each person can take up only 1 subtask)
- [ ] GUI using C++
- [x] Using HTML + JS (+ CSS if needed)
- [x] GUI using Python
- [x] GUI using Java

### Resources
[BMI formula and categories](https://www.ramsayhealth.co.uk/weight-loss-surgery/bmi/bmi-formula)

### Directory Structure
Within this repository's 'development' folder, create a folder called '8_BMI' (if it doesn't exist yet). Within this folder, place the file/folder in which you have written the program for the task, named appropriately.

#### Note
1. Please claim the issue first by commenting here before starting to work on it. While claiming the issue, make sure you specify which of the subtasks you are taking up.
2. Once you are done with the task and have created a Pull Request, please tag @krithikvaidya to request a review.

**Comment by KushGrandhi** [comment]
@krithikvaidya 
i want to do gui with python

**Comment by sakkshm** [comment]
Hey @krithikvaidya , I would like to do it with HTML,CSS and JS ! Please assign that to me.

**Comment by chakravarthi-v** [comment]
hey @krithikvaidya 
I want to do it with java with android studio

**Comment by mayukh-B** [comment]
Hey @krithikvaidya , I would to like to work using HTML and JS . Can you please assign the task to me .

**Comment by krithikvaidya** [comment]
@KushGrandhi @sakkshm @chakravarthi-v, sure go ahead.
@mayukh-B, someone has already claimed the HTML + JS one... You can take up another one if interested.

**Comment by sakkshm** [comment]
I completed the web tasks in #27

**Comment by KushGrandhi** [comment]
@krithikvaidya i completed the gui for python in #32

**Comment by chakravarthi-v** [comment]
@krithikvaidya  I have completed #34

**Comment by krithikvaidya** [comment]
@sakkshm @KushGrandhi @chakravarthi-v great, the PRs will be reviewed and merged in a few days
