### ISSUE TITLE
Maximum XOR subarray using Trie

### ISSUE THREAD

**Issue by DeltaCube23** [WebClub-NITK/Hacktoberfest-2k20#85]
### Description
Given an array of integers find the maximum XOR subarray value using a Trie.

### Details
- Technical Specifications: C/C++
- Type of issue: Single
- Time Limit: 24 hours

### Issue requirements / progress
- Make sure the code is efficient

### Directory Structure
Create a new folder called "85_Maximum_Subarray_XOR" inside algorithms folder and add all the code related to this issue in algorithms/85_Maximum_Subarray_XOR.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @DeltaCube23 to request a review.

**Comment by KangHyeoni** [comment]
Hi @DeltaCube23 , can I work on this?

**Comment by DeltaCube23** [comment]
@KangHyeoni yeah do go ahead

**Comment by KangHyeoni** [comment]
@DeltaCube23 Could you review my PR?

**Comment by DeltaCube23** [comment]
@krithikvaidya please merge it
