### ISSUE TITLE
Implement a solution to the Dining Philosophers problem

### ISSUE THREAD

**Issue by suhasks123** [WebClub-NITK/Hacktoberfest-2k20#86]
### Description
The Dining Philosophers problem is a popular problem in process synchronization in operating systems. Implement a solution to this problem.

### Details
- Technical Specifications:
- Type of issue: Single
- Time Limit: 24 hrs

### Issue requirements / progress
- [ ] Write a program that solves the Dining Philosophers problem

The preferred languages are C/C++. Threads can be used to simulate the philosophers and semaphores can be used as the basis of the solution.

### Resources
https://en.wikipedia.org/wiki/Dining_philosophers_problem

### Directory Structure
Inside the 'Systems' folder in this repository, create a folder called '86_Dining_Philosophers' (if it doesn't exist yet). Place the program containing the solution inside this folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @suhasks123 to request a review.

**Comment by SPandeyCodes** [comment]
Hi @suhasks123 . I would like to work on this issue. Please assign this to me.

**Comment by suhasks123** [comment]
@SPandeyCodes Sure, you can start working on the issue
