### ISSUE TITLE
Given an IPv4 Address, find its class

### ISSUE THREAD

**Issue by krithikvaidya** [WebClub-NITK/Hacktoberfest-2k20#88]
### Description
Assuming classful addressing, given an IPv4 address, find its address class. If the entered IP address is invalid, your program should output an appropriate error message. Please follow the Input / Output format as shown below:

Example:
`Enter the IPv4 address: 194.200.20.55`
`This is a class C IPv4 address.`

### Details
- Technical Specifications: The task should be done in any of the below-mentioned programming languages. Please note that you should submit only a single file containing the code, and nothing else.
- Type of issue: Multiple
- Time Limit: 2 Days

### Issue requirements / progress
- [ ] Dart
- [ ] PHP
- [x] Swift
- [x] Ruby
- [x] Kotlin
- [x] C
- [x] C++
- [x] C#
- [x] Java
- [x] Javascript
- [x] Python
- [x] Golang

### Resources
[Classful Addressing](https://www.geeksforgeeks.org/introduction-of-classful-ip-addressing/)

### Directory Structure
Within this repository's 'Systems' folder, create a folder called 'IPv4_Class' (if it doesn't exist yet). Within this folder, place the file in which you have written the program for the task. The file name should be the name of the language you are using (e.g. - C.c, Python.py)

#### Note
Please claim the issue first by commenting here before starting to work on it. While claiming it, please mention the language that you will be using. Also, please check the checklist above and go through the comments to make sure that you aren't using the same language as someone else.
While submitting a PR, request a review from @krithikvaidya
Doubts and clarifications are welcome.

**Comment by GSantos23** [comment]
I would like to work on this one. Language: Python

**Comment by krithikvaidya** [comment]
Great, go ahead @GSantos23

**Comment by saptarsi96** [comment]
I would like to work on this one. Language: C++

**Comment by krithikvaidya** [comment]
Sure, go ahead @saptarsi96

**Comment by WilliamNewt** [comment]
I would like to work on this in Java if that's alright?

**Comment by krithikvaidya** [comment]
Sure @Infinityz

**Comment by edoardottt** [comment]
[C and Java code](https://www.geeksforgeeks.org/program-determine-class-network-host-id-ipv4-address/)

**Comment by Athi223** [comment]
i would like to contribute for JavaScript

**Comment by ALoserIsMe** [comment]
I have just completed it for JavaScript, but since @Athi223 claimed it I don't mind if they are the one who gets to contribute

**Comment by ALoserIsMe** [comment]
I'd like to contribute for PHP if possible

**Comment by Athi223** [comment]
> I have just completed it for JavaScript, but since @Athi223 claimed it I don't mind if they are the one who gets to contribute

I just had the same problem yesterday mate, so I started claiming before starting so code. Cheers!

**Comment by deepakumarvu** [comment]
I would like to claim for Language: C.

**Comment by krithikvaidya** [comment]
> I have just completed it for JavaScript, but since @Athi223 claimed it I don't mind if they are the one who gets to contribute

Yeah, don't forget to claim it next time :). For now, you can also submit a PR for the code you've written

**Comment by krithikvaidya** [comment]
@syk007 Sure, go ahead

**Comment by aolaria** [comment]
I would like to do it using Go.

**Comment by krithikvaidya** [comment]
Sure @aolaria

**Comment by sakshidhamne** [comment]
I would like to contribute for Python, as it seems the one who requested for it earlier hasn't responded since 14hours

**Comment by GSantos23** [comment]
I am still working on it.

**Comment by aolaria** [comment]
> Sure @aolaria

done!

**Comment by WilliamNewt** [comment]
Could I work on C#?

**Comment by krithikvaidya** [comment]
Sure

**Comment by shwhite17** [comment]
i would like to implement it in dart

**Comment by ALoserIsMe** [comment]
Can I try this in Swift?

**Comment by LazybuddyNK** [comment]
I would like to work on it, language : python

**Comment by krithikvaidya** [comment]
> Can I try this in Swift?

Sure, go ahead @ALoserIsMe 

@LazybuddyNK, sorry, Python has already been done.

**Comment by LazybuddyNK** [comment]
I would like to work on it, language : Kotlin

**Comment by krithikvaidya** [comment]
Go ahead @LazybuddyNK

**Comment by bhawesh96** [comment]
@krithikvaidya , I'll do it in Ruby
