### ISSUE TITLE
Server-Client System Using Socket Programming

### ISSUE THREAD

**Issue by AnorexicAtticusFinch** [WebClub-NITK/Hacktoberfest-2k20#9]
### Description
Create a C/C++ program to make a server that listens for a client at a certain port. Create a C/C++ program to make a client that tries to connect to the server on the same port (The server and client will be running on the same system). The client sends the name of file to the server (Take the filename as input from the user). If the file exists on the server, the server will return it's contents to the client otherwise it will return an error message to the client. The client will print what the server returns to the screen.

### Details
- Technical Specifications: C/C++
- Type of issue: Single
- Time Limit: 3 days

### Issue requirements / progress
- [ ] Create the server.
- [ ] Create the client.

### Resources
https://www.geeksforgeeks.org/socket-programming-cc/
https://www.geeksforgeeks.org/tcp-server-client-implementation-in-c/
https://www.csd.uoc.gr/~hy556/material/tutorials/cs556-3rd-tutorial.pdf

### Directory Structure
Create a new folder called "9_Socket_Programming" inside the systems folder and add all code related to this issue in the systems/9_Socket_Programming folder.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @AnorexicAtticusFinch to request a review.

**Comment by raypretam** [comment]
I want to work on this issue. Please assign it to me.

**Comment by AnorexicAtticusFinch** [comment]
> I want to work on this issue. Please assign it to me.

Okay, go ahead and start working on it.

**Comment by praj1wal** [comment]
I want to work on this issue.

**Comment by krithikvaidya** [comment]
Since @raypretam hasn't yet submitted a PR for this, you can go ahead @praj1wal.
